---
title: "A Guide to the docket Package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{docket_guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
##
## Introduction
##

Use 'docket' to insert data from an R environment into a template document by replacing user generated flags.


##
## Setup
##

Create a template document in a program such as Word. Identify where you would like a R data to be inserted and add a string enclosed by the characters « » (Example: «FirstName», «LastName», «Address»).


##
## Create a Dictionary
##

A dictionary is a two-column data frame with the first containing the flags identified in the template document, and the second containing the data to replace each flag. Use getDictionary() on a file path to generate that document's dictionary.

#Example: 
#my_dictionary <- getDictionary("C:/Users/public/Desktop/monthly_report.docx")


##
## Validate Dictionary Meets Requirements (optional)
##

Use checkDictionary() to ensure that your dictionary meets the requirements to be processed into the document. 

The requirements for a dictionary are:
1. It is a data frame containing 2 columns
2. The first column is named "flag"
3. Each entry in the first column is a string surrounded by flag wings («»)

Note: While it's not required for a dictionary to be generated by getDictionary(), dictionaries not meeting these requirements will be rejected.

#Example:
#my_dictionary <- getDictionary("C:/Users/public/Desktop/monthly_report.docx")
#
#my_dictionary[,2] <- paste("observation", 1:nrow(my_dictionary))
#
#checkDictionary(my_dictionary)
#TRUE


##
## Process dictionary into template document
##

Use docket() to replace the identified flags in the template with R data. Uses the input arguments of the template file, dictionary, and output file path and name.

#Example:
#docket("C:/Users/public/Desktop/monthly_report.docx", my_dictionary, "C:/Users/public/Desktop/finished_report.docx")
#Replaces flags and creates a new document.

